name: redq.ME
favicon: null
layout_spectrum: 0.39145
typography_spectrum: 0.7503703671973199
title: Things I make and the things that make me
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75056967-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2F3A4C'
    - '#5380BD'
    - '#9ABBE2'
    - '#C5B599'
    - '#FFE1BC'
  brandStrength: 0.232984276721254
  lightness: 0.6770211770199239
  saturation: 0.6844199181068689
  rhythmicContrast: 0.2378319269046187
purpose: []
