name: redq.ME
favicon: null
layout_spectrum: 0.47325322730466723
typography_spectrum: 0.7503703671973199
title: Things I make and the things that make me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75056967-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b8e8a'
    - '#4c535d'
    - '#a6b3aa'
    - '#dfe2d7'
    - '#2a3046'
  brandStrength: 0.232984276721254
  lightness: 0.6770211770199239
  saturation: 0.6844199181068689
  rhythmicContrast: 0.23783192690461874
purpose: []
